# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20171027_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_data',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
